export const TODOS_PRODUTOS = 'TODOS_PRODUTOS';
export const TODOS_PRODUTOS_SUCESSO = 'TODOS_PRODUTOS_SUCESSO';

export const PRODUTO_POR_ID = 'PRODUTO_POR_ID';
export const PRODUTO_POR_ID_SUCESSO = 'PRODUTO_POR_ID_SUCESSO';

export const ADICIONAR_PRODUTO = 'ADICIONAR_PRODUTO';
export const ADICIONAR_PRODUTO_SUCESSO = 'ADICIONAR_PRODUTO_SUCESSO';

export const ATUALIZAR_PRODUTO = 'ATUALIZAR_PRODUTO';
export const ATUALIZAR_PRODUTO_SUCESSO = 'ATUALIZAR_PRODUTO_SUCESSO';

export const REMOVER_PRODUTO = 'REMOVER_PRODUTO';
export const REMOVER_PRODUTO_SUCESSO = 'REMOVER_PRODUTO_SUCESSO';

export const TODOS_FABRICANTES = 'TODOS_FABRICANTES';
export const TODOS_FABRICANTES_SUCESSO = 'TODOS_FABRICANTES_SUCESSO';

export const TODOS_LIVROS = 'TODOS_LIVROS';
export const TODOS_LIVROS_SUCESSO = 'TODOS_LIVROS_SUCESSO';

export const LIVRO_POR_ID = 'LIVRO_POR_ID';
export const LIVRO_POR_ID_SUCESSO = 'LIVRO_POR_ID_SUCESSO';

export const ADICIONAR_LIVRO = 'ADICIONAR_LIVRO';
export const ADICIONAR_LIVRO_SUCESSO = 'ADICIONAR_LIVRO_SUCESSO';
